name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose --version
        # continue-on-error: true

      - name: Build Docker Image
        run: |
          docker-compose build
        # continue-on-error: true
        
